apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\marco.mazzei\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f compose.yaml
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: gradio-visao
  name: gradio-visao
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: gradio-visao
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\marco.mazzei\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f compose.yaml
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: gradio-visao
    spec:
      containers:
        - image: mamazzei/gradio-visao
          name: gradio-visao
          ports:
            - containerPort: 7861
              protocol: TCP
      restartPolicy: Always
