apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\marco.mazzei\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f compose.yaml
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: gradio-visao
  name: gradio-visao
spec:
  type: LoadBalancer
  ports:
    - name: "7861"
      port: 7861
      targetPort: 7861
  selector:
    io.kompose.service: gradio-visao
