server {
    listen 3000;
    root /usr/share/nginx/html;
    index index.html;

    # Necessário para o React Router funcionar com refresh na página
    location / {
        try_files $uri $uri/ /index.html;
    }
}
